default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rails_app_development # データベース名 (docker-compose.yml と一致させる)

test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  database: rails_app_production